#include "Voiture.h"




bool Voiture::rouler (int gaz )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98--125--5f54b9e4:18bcccb2114:-8000:0000000000000C3B begin
{
    return false;
}
// section 10--28--98--125--5f54b9e4:18bcccb2114:-8000:0000000000000C3B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
