#include "Cercle.h"
#include <cmath>
#include <iostream>

const double PI = 3.14159265358979323846;

Cercle::Cercle()
{
}


Cercle::Cercle(double diametre,double x2)
{
    std::cout << " constructeur de Cercle  \n" << std::endl;
    diametre = 0;

}

double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
{
    Surface = PI * pow((diametre / 2), 2);

    return (Surface);
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
{
    Perimetre  =  2 * PI * (diametre / 2);

    return (Perimetre); 
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
