#include "TriangleRectangle.h"
#include <cmath>
#include <iostream>

TriangleRectangle::TriangleRectangle()
{
}

TriangleRectangle::TriangleRectangle(double base, double hauteur)
{
    std::cout << " constructeur de TriangleRectangle  \n" << std::endl;
    base = 0;
    hauteur = 0;
}

double TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D60 begin
{
    Surface = (base * hauteur) / 2;
    return(Surface);
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D64 begin
{
    // Calculer la longueur de l'hypoténuse en utilisant le théorème de Pythagore
    double hypothenuse = sqrt(base * base + hauteur * hauteur);

    // Calculer le périmètre en additionnant les trois côtés
    Perimetre = base + hauteur + hypothenuse;

    return Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
