#include "Utilisateur.h"
#include "FormesGeometriques.h"
#include "TriangleRectangle.h"
#include "Cercle.h"
#include "Rectangle.h"
#include <iostream>		//"<>" car librairie standard (pas créé par l'utilisateur)
#include <cstdint>		//lib types normalisés c++ (types entiers) exemples: bool,char,short,int,long
#include <string>		//Pour utiliser les string








void Utilisateur::AfficherResultats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
{
    if (m_CodeFormeChoisie == 0)
    {
        std::cout << "Pour un TriangleRectangle base = " << m_x1
            << " hauteur = " << m_x2 << " surface = " << myFormesGeometriques->GetSurface()
            << " perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
        
    }
    else if (m_CodeFormeChoisie == 1)
    {
        std::cout << "Pour un Rectangle la largeur = " << m_x1
            << " hauteur = " << m_x2 << " surface = " << myFormesGeometriques->GetSurface()
            << " perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
        
    }
    else if (m_CodeFormeChoisie == 2)
    {
        std::cout << "Pour un Cercle diametre = " << m_x1
            << " surface = " << myFormesGeometriques->GetSurface()
            << " perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;  
    }
    else
    {
        std::cout << "Erreur  \n" << std::endl;
        //default
    }  
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Utilisateur::ChoisirForme(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
{
    m_CodeFormeChoisie = CodeForme;

    if (m_CodeFormeChoisie == 0)
    {
         myFormesGeometriques = new TriangleRectangle(m_x1, m_x2);
    }
    else if (m_CodeFormeChoisie == 1)
    {
        myFormesGeometriques = new Rectangle(m_x1, m_x2);
    }
    else if (m_CodeFormeChoisie == 2)
    {
        myFormesGeometriques = new Cercle(m_x1, m_x2);
    }
    else
    {
        std::cout << "Erreur ChoisirForme \n" << std::endl;
        //default
    }

    
    return 0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::SaisirLesParametres()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
{
    if (m_CodeFormeChoisie == 0)
    {
        std::cout << "entree la base du triangle rectangle \n" << std::endl;    //Flux de sortie
        std::cin >> m_x1;	//Flux d'entrée

        std::cout << "entree la hauteur du triangle rectangle \n" << std::endl;    //Flux de sortie
        std::cin >> m_x2;	//Flux d'entrée
    }
    else if (m_CodeFormeChoisie == 1)
    {
        std::cout << "entee la largeur du rectangle \n" << std::endl;    //Flux de sortie
        std::cin >> m_x1;	//Flux d'entrée

        std::cout << "entree la hauteur du rectangle \n" << std::endl;    //Flux de sortie
        std::cin >> m_x2;	//Flux d'entrée
        
    }
    else if (m_CodeFormeChoisie == 2)
    {
        std::cout << "entree le diamettre du Cercle  \n" << std::endl;    //Flux de sortie
        std::cin >> m_x1;	//Flux d'entrée
        m_x2 = 0;	
    }
    else
    {
        std::cout << "Erreur SaisirLesParametres \n" << std::endl;
        //default
    }   
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ExecuterLesCalculs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
{  
    myFormesGeometriques->CalculerPerimetre(m_x1, m_x2);
    myFormesGeometriques->CalculerSurface(m_x1, m_x2);
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
