using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EX4_CS
{
    class Cercle : FormesGeometriques
    {
        //atribut 


        public Cercle() { }

        public Cercle (double diametre, double x2)
        {
            Console.WriteLine(" constructeur de Cercle  \n");

            diametre = 0;
        }

        public double CalculerSurface(double diametre)
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
        {
          
            Surface = Math.PI * Math.Pow((diametre / 2), 2);

             return (Surface);
        }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

        public double CalculerPerimetre(double diametre)
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
        {
            Perimetre = 2 * Math.PI * (diametre / 2);

            return (Perimetre);
        }





    }
}
