using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EX4_CS
{
    public class FormesGeometriques
    {

        //atribut 

        protected double Surface;
        protected double Perimetre;

        public FormesGeometriques() { }

        public FormesGeometriques(double x1, double x2)
        {
            
            Console.WriteLine(" constructeur de FormesGeometriques  \n");

            x1 = 0;
            x2 = 0;
        }




    public virtual double CalculerSurface(double x1, double x2)
    // don't delete the following line as it's needed to preserve source code of this autogenerated element
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 begin
    {
        return Surface;
    }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

    public virtual double CalculerPerimetre(double x1, double x2)
    // don't delete the following line as it's needed to preserve source code of this autogenerated element
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 begin
    {
        return Perimetre;
    }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

    public double GetSurface()
    // don't delete the following line as it's needed to preserve source code of this autogenerated element
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D begin
    {

        return Surface;
    }
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D end
    // don't delete the previous line as it's needed to preserve source code of this autogenerated element

    public double GetPerimetre()
    // don't delete the following line as it's needed to preserve source code of this autogenerated element
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F begin
    {
        return Perimetre;
    }
    // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F end
    // don't delete the previous line as it's needed to preserve source code of this autogenerated element




}
}
