using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EX4_CS
{
    class Utilisateur
    {
        //atribut

        private int  m_CodeFormeChoisie;
        private double m_x1, m_x2;

        FormesGeometriques myFormesGeometriques = new FormesGeometriques();


        public void AfficherResultats()
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
        {
            if (m_CodeFormeChoisie == 0)
            {
                Console.WriteLine("Pour un TriangleRectangle base = %f hauteur = %f surface = %f perimetre =%f \n"
                    , m_x1, m_x2, myFormesGeometriques.GetSurface(), myFormesGeometriques.GetPerimetre());
          

            }
            else if (m_CodeFormeChoisie == 1)
            {
                Console.WriteLine("Pour un Rectangle la largeur = %f hauteur = %f surface = %f perimetre = %f \n ",
                    m_x1, m_x2 , myFormesGeometriques.GetSurface(), myFormesGeometriques.GetPerimetre());

            }
            else if (m_CodeFormeChoisie == 2)
            {

                Console.WriteLine("Pour un Cercle diametre = %f surface = %f perimetre = %f \n ",
                    m_x1, myFormesGeometriques.GetSurface(), myFormesGeometriques.GetPerimetre());
            }
            else
            {
                Console.WriteLine ("Erreur  \n");
                //default
            }
        }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

        public int ChoisirForme(int CodeForme)
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
        {
            m_CodeFormeChoisie = CodeForme;

            if (m_CodeFormeChoisie == 0)
            {
                TriangleRectangle myFormesGeometriques = new TriangleRectangle(m_x1, m_x2);
            }
            else if (m_CodeFormeChoisie == 1)
            {
                Rectangle myFormesGeometriques = new Rectangle(m_x1, m_x2);
            }
            else if (m_CodeFormeChoisie == 2)
            {
                Cercle myFormesGeometriques = new Cercle(m_x1, m_x2);
            }
            else
            {
                Console.WriteLine( "Erreur ChoisirForme \n");
                //default
            }


            return 0;
        }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

        public void SaisirLesParametres()
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
        {
            if (m_CodeFormeChoisie == 0)
            {
                Console.WriteLine("entree la base du triangle rectangle \n");    //Flux de sortie
                 m_x1 = Console.Read();   //Flux d'entrée

                Console.WriteLine("entree la hauteur du triangle rectangle \n");    //Flux de sortie
                m_x2 = Console.Read();   //Flux d'entrée
            }
            else if (m_CodeFormeChoisie == 1)
            {
                Console.WriteLine("entee la largeur du rectangle \n" );    //Flux de sortie
                m_x1 = Console.Read();   //Flux d'entrée

                Console.WriteLine("entree la hauteur du rectangle \n");    //Flux de sortie
                m_x2 =  Console.Read();   //Flux d'entrée

            }
            else if (m_CodeFormeChoisie == 2)
            {
                Console.WriteLine( "entree le diamettre du Cercle  \n");    //Flux de sortie
                m_x1 = Console.Read();   //Flux d'entrée
                m_x2 = 0;
            }
            else
            {
                Console.WriteLine( "Erreur SaisirLesParametres \n");
                //default
            }
        }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element

        public void ExecuterLesCalculs()
        // don't delete the following line as it's needed to preserve source code of this autogenerated element
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
        {
            myFormesGeometriques.CalculerPerimetre(m_x1, m_x2);
            myFormesGeometriques.CalculerSurface(m_x1, m_x2);
        }
        // section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
        // don't delete the previous line as it's needed to preserve source code of this autogenerated element







    }
}
