#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
