#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
