#include "Utilisateur.h"
#include "FormesGeometriques.h"
#include "TriangleRectangle.h"





void Utilisateur::AfficherResultats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
{
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Utilisateur::ChoisirForme(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
{
    if (m_CodeFormeChoisie == 0)
    {
         myFormesGeometriques = new TriangleRectangle();
    }
    else if (m_CodeFormeChoisie == 1)
    {
        myFormesGeometriques = new Rectangle();
    }
    else if (m_CodeFormeChoisie == 2)
    {
        myFormesGeometriques = new Cercle();
    }

    
    return 0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::SaisirLesParametres()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
{
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ExecuterLesCalculs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
{
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
